services:
  mysql:
      container_name: mysqldb
      image: mysql:8.0
      volumes:
        - demo-data:/var/lib/mysql
      environment: 
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: buy-and-sell
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 10s
        timeout: 5s
        retries: 5

  phpmyadmin:
      image: phpmyadmin
      ports:
        - "8080:80"
      environment:
        PMA_HOST: mysql
        PMA_USER: root
        PMA_PASSWORD: secret
        PMA_PORT: 3306
  backend:
      build:
        context: ./
        target: backend-dev
      depends_on: 
        mysql:
          condition: service_healthy
      ports: 
        - "8000:8000"
      environment:
        MYSQL_HOST: mysql
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
        MYSQL_DB: buy-and-sell
        GOOGLE_APPLICATION_CREDENTIALS: /usr/local/app/backend/credentials.json
      develop:
        watch:
          - path: ./backend/src
            action: rebuild
            target: /usr/local/app/backend/src
          - path: ./backend/package.json
            action: rebuild
  client:
      build:
        context: ./
        target: client-dev
      depends_on:
         - backend
      ports:
        - "4201:4200"
      develop:
        watch:
          - path: ./client/src
            action: sync
            target: /usr/local/app/client/src
          - path: ./client/package.json
            action: rebuild
volumes:
  demo-data:
